### ISSUE TITLE
configure file is not suite new jdk lib path and then configure error

### ISSUE THREAD

**Issue by TowerLee** [ray2501/tclBlend#1]
configure file is not suite new jdk lib path，such as  in path /jre/lib/aarch64/client  no ljvm so；no  jre/lib/$machine/native_threads this path，
on amd64 just run next if branch，it run ok；but now build on arm64  occur error；

Using the following JNI library flags -L/usr/bin/jdk-8u191/jre/lib/aarch64 -ljava -lverify -L/usr/bin/jdk-8u191/jre/lib/aarch64/client -ljvm -L/usr/bin/jdk-8u191/jre/lib/aarch64/native_threads -lhpi
Using the following runtime library path /usr/bin/jdk-8u191/jre/lib/aarch64:/usr/bin/jdk-8u191/jre/lib/aarch64/client:/usr/bin/jdk-8u191/jre/lib/aarch64/native_threads
Using LD_PRELOAD=
Using LD_BIND_NOW=
configure:4021: checking to see if we can link a JNI application
configure:4056: gcc -pipe -o conftest -g -O2 -I/usr/bin/jdk-8u191/include -I/usr/bin/jdk-8u191/include/linux   conftest.c  -L/usr/bin/jdk-8u191/jre/lib/aarch64 -ljava -lverify -L/usr/bin/jdk-8u191/jre/lib/aarch64/client -ljvm -L/usr/bin/jdk-8u191/jre/lib/aarch64/native_threads -lhpi >&5
/usr/bin/ld: cannot find -ljvm
/usr/bin/ld: cannot find -lhpi
collect2: error: ld returned 1 exit status

**Comment by ray2501** [comment]
I update tcljava.m4 and configure file for this issue. Please help to check the change is OK.

**Comment by TowerLee** [comment]
The modify work fine;  Thanks
by way ask next release version time ?  Thanks so much if release as soon
